name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pip=24.0
  - scikit-learn=1.5.1
  - scipy=1.10
  - pandas=1.5.3
  - pip:
    - inference-schema[numpy-support]==1.3.0
    - xlrd==2.0.1
    - mlflow
    - azureml-core
    - azureml-mlflow
    - psutil
    - tqdm
    - ipykernel~=6.29
    - matplotlib
